
services:
  camergd-api:
    build: .
    ports:
      - 3007:3007
    env_file:
      - .env.production
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - camergd-network
  
  postgis:
    image: postgis/postgis:15-3.3
    restart: always
    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
    networks:
      - camergd-network


networks:
  camergd-network:
    name: camergd-network

volumes:
  postgis_data: